apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rihaboueslati
  name: exam-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
